# Generated by Django 3.0 on 2019-12-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Button', to_field='name'),
        ),
    ]
