# Generated by Django 3.0 on 2019-12-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20191214_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='referral',
            field=models.ManyToManyField(to='bot.Profiles'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
