# Generated by Django 3.0 on 2019-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20191215_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
