# Generated by Django 3.0 on 2019-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20191216_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
