# Generated by Django 3.0 on 2019-12-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20191226_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='details',
        ),
    ]
